import { type NextPage } from "next";
import Head from "next/head";
import PageWrapper from "../components/pageWrapper";

const Home: NextPage = () => {
  return (
    <PageWrapper>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </PageWrapper>
  );
};

export default Home;
