import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import DiaryRecord from "../components/diaryRecord";
import PageWrapper from "../components/pageWrapper";
import { getServerAuthSession } from "../server/auth";
import { api } from "../utils/api";
import { dayts } from "../utils/day";

const Home: NextPage = ({}) => {
const {data, hasNextPage, fetchNextPage, isFetching} = api.records.listRecords.useInfiniteQuery({limit: 10}, {getNextPageParam: (lastPage) => lastPage.nextCursor});

// useInfiniteQuery return data in groups the size of the set limit... Annoying AF unless flatmapped into one long array... 
const records = data?.pages.flatMap((page) => page.records) ?? [];

  return (
    <PageWrapper showHeader={true}>
      <Head>
        <title>UpShop - Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full flex-col w-full gap-2">
        {records.map((record, i) => {
          return (
            <DiaryRecord
              key={i}
              name={record.user.name}
              language={record.programmingLanguage}
              duration={dayts.duration(record.timeSpent).asMinutes()}
              date={record.date}
              description={record.description}
              rating={record.rating}
            />
          );
        })}

         {hasNextPage && !isFetching ? (
        <button
          className="mb-40 mt-4 w-full rounded-md bg-green-500 py-4 text-lg font-bold text-white"
          onClick={() => {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
            fetchNextPage().catch((err: any) => console.log(err));
          }}
        >
          Load more records
        </button>
      ) : (
        <span className="mb-40 mt-4 text-center">{"No more records :("}</span>
      )}
      </main>
    </PageWrapper>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerAuthSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/signin",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}

export default Home;
